spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: supplyservice-config-client-dev
---
spring:
  profiles: test
  application:
    name: supplyservice-config-client-test
